version: "2"

services:
  django:
    image: django_pg:1.0
    build: .
    command: >
      sh -c "cd /app &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/:/app/
      - ./logs/:/logs/
      - ./service/:/service/
      - ./crontab/:/crontab/
    ports:
      - ${WEB_PORT}:8000
    environment:
      - DEBUG=1
#      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
    env_file:
      - ./src/.env
    depends_on:
      - postgres

  celery:
    image: django_pg:1.0
    build: .
    command: >
      sh -c "cd /app &&
             celery -A backend worker -l info"
    volumes:
      - ./src/:/app/
      - ./logs/:/logs/
      - ./service/:/service/
      - ./crontab/:/crontab/
    environment:
      - DEBUG=1
    #      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
    env_file:
      - ./src/.env
    depends_on:
      - django
      - redis

#  celery-beat:
#    image: django_pg:1.0
#    build: .
#    command: >
#      sh -c "cd /app &&
#             celery -A backend beat -l info"
#    volumes:
#      - ./src/:/app/
#      - ./logs/:/logs/
#      - ./service/:/service/
#      - ./crontab/:/crontab/
#    environment:
#      - DEBUG=1
#    #      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
#    env_file:
#      - ./src/.env
#    depends_on:
#      - django
#      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

    ports:
      - "6379:6379"

    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  pgdata:
