version: "2"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
